server:
  port: 8082

spring:
  application:
    name: notification-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:55432/market_app}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  rabbitmq:
    host: ${RABBITMQ_HOST:127.0.0.1}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

app:
  notifications:
    exchange: ${NOTIFICATIONS_EXCHANGE:market.notifications}
    routing-key: ${NOTIFICATIONS_ROUTING_KEY:orders.events}
    queue: ${NOTIFICATIONS_QUEUE:notification.events}
