server:
  port: 8085

spring:
  application:
    name: api-gateway

nova:
  routes:
    market-app-url: ${MARKET_APP_URL:http://localhost:8080}
    market-file-service-url: ${MARKET_FILE_SERVICE_URL:http://localhost:8081}
    notification-service-url: ${NOTIFICATION_SERVICE_URL:http://localhost:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  pattern:
    level: "%5p [requestId:%X{requestId:-none}]"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Market App API
        url: http://localhost:8080/v3/api-docs
      - name: File Service API
        url: http://localhost:8081/v3/api-docs
      - name: Notification Service API
        url: http://localhost:8082/v3/api-docs
      - name: API Gateway
        url: /v3/api-docs
